<a href="https://colab.research.google.com/github/reeda23/Deep-Learning-With-Pytorch/blob/main/1_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started with Pytorch

In [38]:
import torch
import numpy as np

**PyTorch: Tensors**
A PyTorch Tensor is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic n-dimensional array to be used for arbitrary numeric computation.
[To read more about tensors see the offical documentation](https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_tensor.html)


In [3]:
#scaler value
x = torch.empty(1)

#this will print empty tensor whose value is not initialized yet
print(x)

tensor([9.9642e-35])


In [4]:
#1D vector with 3 elements

x = torch.empty(3)
print(x)

tensor([9.9671e-35, 0.0000e+00, 1.5975e-43])


In [5]:
#2D Matrix

x= torch.empty(2,3)
print(x)

tensor([[9.9678e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00]])


In [6]:
#3D Matrix

x = torch.empty(2,2,3)
print(x)

tensor([[[9.9680e-35, 0.0000e+00, 1.5975e-43],
         [1.3873e-43, 1.4574e-43, 6.4460e-44]],

        [[1.4153e-43, 1.5274e-43, 1.5695e-43],
         [1.6255e-43, 1.6956e-43, 3.7404e-14]]])


In [7]:
#4D Matrix

x = torch.empty(2,2,2,3)
print(x)

tensor([[[[9.7779e-35, 0.0000e+00, 7.0065e-44],
          [7.0065e-44, 6.3058e-44, 6.7262e-44]],

         [[7.4269e-44, 6.3058e-44, 7.0065e-44],
          [7.1466e-44, 1.1771e-43, 6.7262e-44]]],


        [[[7.4269e-44, 8.1275e-44, 6.7262e-44],
          [7.0065e-44, 8.1275e-44, 7.1466e-44]],

         [[7.2868e-44, 6.4460e-44, 7.5670e-44],
          [7.1466e-44, 6.7262e-44, 7.9874e-44]]]])


In [9]:
#can create tensor with random values

x = torch.rand(2,3)
x

tensor([[0.6064, 0.7043, 0.7698],
        [0.4130, 0.5882, 0.7092]])

In [10]:
#matrix with all zeros

x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [14]:
#matrix with all ones

x = torch.ones(2,3)
print(x)

#if you want to see the datatype
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [15]:
#we can also specify data type

x = torch.ones(2,2, dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [16]:
#to see the size, Note:size is a function

import torch

x = torch.ones(2,2, dtype= torch.float16)
print()
print(x.size())

torch.Size([2, 2])


In [17]:
#creating tensor/array/matrix with some list

x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


# Basic Arithmetic Operations

In [18]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.6708, 0.4070],
        [0.2610, 0.1599]])
tensor([[0.3750, 0.2553],
        [0.2888, 0.6070]])


In [20]:
#simple element-wise addition
z = x + y
print(z)

tensor([[1.0458, 0.6624],
        [0.5498, 0.7669]])


In [23]:
#another way of adding
z = torch.add(x,y)
print(z)

tensor([[1.0458, 0.6624],
        [0.5498, 0.7669]])


In [24]:
# can also do inplace addition
# Note: In pytorch every function that has trailing _ will perform inplace operation
y.add_(x)

#modify the elements of y
print(y)

tensor([[1.0458, 0.6624],
        [0.5498, 0.7669]])


In [25]:
#element-wise subtraction
z = x - y
print(z)

tensor([[-0.3750, -0.2553],
        [-0.2888, -0.6070]])


In [26]:
#another way of doing subtraction
z = torch.sub(x, y)
print(z)

tensor([[-0.3750, -0.2553],
        [-0.2888, -0.6070]])


In [27]:
#element-wise multiplication
z = x*y
print(z)

tensor([[0.7015, 0.2696],
        [0.1435, 0.1226]])


In [28]:
#alternate way
z = torch.mul(x,y)
print(z)

tensor([[0.7015, 0.2696],
        [0.1435, 0.1226]])


In [30]:
#element-wise division

z = torch.div(x,y)
print(z)

tensor([[0.6414, 0.6145],
        [0.4747, 0.2085]])


# Slicing Operations

In [31]:
#can use slicing operations just like numpy array

x = torch.rand(5,3)
print(x)

tensor([[0.7407, 0.7211, 0.5337],
        [0.3072, 0.6715, 0.6984],
        [0.4830, 0.9436, 0.3622],
        [0.3045, 0.7659, 0.8795],
        [0.9034, 0.9612, 0.3314]])


In [32]:
#all rows but one column
print(x[:, 0])

tensor([0.7407, 0.3072, 0.4830, 0.3045, 0.9034])


In [33]:
#only first row but all columns
print(x[1,:])

tensor([0.3072, 0.6715, 0.6984])


In [34]:
#only one value

print(x[1,1])

tensor(0.6715)


In [35]:
#if you want to get the value of tensor
#Note this can only be used if you have only one value in the tensor
print(x[1,1].item())

0.671501636505127


In [37]:
#Reshaping tensor

x = torch.rand(4,4)
print(x)

#can reshape using view method
#now we want 1-dimension only
#no of values should be the same e.g 4x4 = 16 
y = x.view(16)
print(y)

#if we don't want to put dimension we can say, pytorch will automatically 
#determine the right size for it
y = x.view(-1,8)
print(y)

tensor([[0.3026, 0.5617, 0.6261, 0.2885],
        [0.9797, 0.7187, 0.9394, 0.4519],
        [0.7413, 0.5351, 0.5235, 0.3627],
        [0.5201, 0.4051, 0.8699, 0.8866]])
tensor([0.3026, 0.5617, 0.6261, 0.2885, 0.9797, 0.7187, 0.9394, 0.4519, 0.7413,
        0.5351, 0.5235, 0.3627, 0.5201, 0.4051, 0.8699, 0.8866])
tensor([[0.3026, 0.5617, 0.6261, 0.2885, 0.9797, 0.7187, 0.9394, 0.4519],
        [0.7413, 0.5351, 0.5235, 0.3627, 0.5201, 0.4051, 0.8699, 0.8866]])


# Converting from Numpy to Torch Tensor and Vice Versa

In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
#if we want numpy array we can say
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [42]:
print(type(a))
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


Note: If the tensor is on CPU and not on the GPU then both objects will share the same memory location, so this means if we change one it will also change the other

In [44]:
#if we modify a or b in-place
#add 1 to each element of a
a.add_(1)
print(a)

tensor([3., 3., 3., 3., 3.])


In [45]:
print(b)

[3. 3. 3. 3. 3.]


So both changed because they both point to the same memory location

In [46]:
# Other way 

a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [47]:
b = torch.from_numpy(a)

In [48]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [50]:
#if we modify one other will change
#incrementing numpy array by 1
a +=1
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [ ]:
#if you want to specify tensor on gpu

if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device= device)
    y = torch.ones(5)
    y = y.to(device) 
    z = x + y  #now this will perform on GPU
    z.numpy() #if we call this z.numpy() it will create error because numpy can 
    #only handly cpu tensors
    z = z.to("cpu")

By default requies_grad is False, if we want to compute gradients we specify it as True. This means whenever we have a variable in our model that we want to optimize we need gradients.

In [51]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
